#!"C:\Users\Alex\Documents\Python Scripts\Flir_cam_recorder\flir-recorder\Scripts\python.exe"
# EASY-INSTALL-SCRIPT: 'dill==0.3.4','undill'
__requires__ = 'dill==0.3.4'
__import__('pkg_resources').run_script('dill==0.3.4', 'undill')
